parameters:
  logging_level: !php/const Monolog\Logger::INFO

services:
  logger:
    public: true
    class: Monolog\Logger
    arguments:
      - 'handler'
    calls:
      - [pushHandler, ['@logging.handler']]

  logging.formatter:
    class: Monolog\Formatter\LineFormatter
    public: false
    arguments:
      - '%%message%% %%context%% %%extra%%'

  logging.handler:
    class: Monolog\Handler\StreamHandler
    public: false
    arguments:
      - 'php://stderr'
      - '%logging_level%'
    calls:
      - [setFormatter, ['@logging.formatter']]

# Define your own handlers and other services here
  handler.hello:
    public: true
    class: Raines\Serverless\HelloHandler

#  handler.example:
#    class: Acme\ExampleHandler
